### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by justewg** [adrianmanchev/trading-charts#2]
Hello.
Nice application, thanks for publishing.
I have a question - where can I edit main page styles in this app?
It's somewhere in the node-modules package?
For example, I tried to edit media-queries `@media (min-width: 1400px)`, but haven't found it.

**Comment by adrianmanchev** [comment]
Hi @justewg,

You can edit or add your new meta tags, stylesheets and scripts in file which located **public/index.html** or write your own unique style works in any single .vue file using the `<style>` tag. For example **src/views/currencies/Chart.vue**. Please visit guide [Scoped CSS](https://vuejs.org/api/sfc-css-features.html#scoped-css) for more information.

Don't forget compile project by running `npm run build` after finish your own changes.

**Comment by justewg** [comment]
Am I right that currently existing styles - layout, grid etc. - I can edit only reassign by my custom styles in components?
There is no anywhere in project source styles theme ?

**Comment by adrianmanchev** [comment]
Yes, you are right. There is no theme source in this project.
